# File: .github/workflows/ci-placeholder.yml
name: CI Placeholder

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run placeholder step
        run: echo "This is a placeholder status check"

